# http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - osx
  - linux
julia:
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
after_success:
  - julia -e 'cd(Pkg.dir("SPH")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
